### ISSUE TITLE
Photocurrent calculation continues to have problems

### ISSUE THREAD

**Issue by wandell** [isetbio/WLVernierAcuity#4]
The classifier sometimes produces a very high level even when the offset is 0.  Needs more debugging.

**Comment by npcottaris** [comment]
Hi Brian,

I had a similar problem (100% class. performance at ridiculously low contrasts) and I tracked it down to a seed bug in osAddNoise, which I fixed a couple on Feb 14.Have you run the classifier since then?

Nicolas



On Feb 18, 2017, at 12:11 AM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


The classifier sometimes produces a very high level even when the offset is 0. Needs more debugging.

**Comment by wandell** [comment]
That definitely improved but did not fix.  Still hunting.  Maybe we can try together.

 B

Sent from a mobile device

On Feb 17, 2017, at 9:46 PM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Brian,

I had a similar problem (100% class. performance at ridiculously low contrasts) and I tracked it down to a seed bug in osAddNoise, which I fixed a couple on Feb 14.Have you run the classifier since then?

Nicolas



On Feb 18, 2017, at 12:11 AM, Brian Wandell <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


The classifier sometimes produces a very high level even when the offset is 0. Needs more debugging.

**Comment by render-toolbox** [comment]
Another issue Nicolas found is that if your stimulus does not preserve the mean, you can get a different linear filter precomputed and this is difference can be large enough to classify two uniform fields as different.  The fix was to lock the linear filter with the background and pass the same filter on the stimulus interval.  There is now some way to do that, although I don’t know the syntax nor whether it is documented in the header comments.

DB

**Comment by npcottaris** [comment]
Yes I should have mentioned that.

There is already functionality that returns the impulse responses and mean currents computed. This was developed by Brian in order to save on computation time: compute them during trial #1 -  reuse them during all remaining trials.

All I am doing additionally is to compute them during the null stimulus and reuse them during the test stimulus. In our case where the mosaic covered a small area of the grating stimulus this made a very dramatic improvement. But in Vernier patterns it might not.

Happy to hunt together with you Brian using the Vernier stimulus. What is the top level routine that I should start tracking from?

Nicolas


On Feb 18, 2017, at 7:17 AM, Render Toolbox <notifications@github.com<mailto:notifications@github.com>> wrote:

Another issue Nicolas found is that if your stimulus does not preserve the mean, you can get a different linear filter precomputed and this is difference can be large enough to classify two uniform fields as different. The fix was to lock the linear filter with the background and pass the same filter on the stimulus interval. There is now some way to do that, although I don’t know the syntax nor whether it is documented in the header comments.

DB

**Comment by wandell** [comment]
Thanks.  That gives me the right place to look next.  Glad you took care of the noise, now I will  fix up the photocurrent impulse response function issue.  Super helpful.

The behavior I was seeing was that a lot of the time 0 offset difference was at chance as expected. But occasionally 0 offset difference was 70 or 80 percent correct.  If I sent in exactly the same stimulus (not just different samples with 0 offset), always at chance.  But when I sent in two different samples with 0 offset, this could happen.  

The idea that the mean level of the first sample differed, and this causes the impulse response to differ, and the SVM picks this up, is extremely plausible.  Will report back.

**Comment by wandell** [comment]
Thanks to everyone.  I finally got some programming time today. By fixing the interpFilters and meanCur for the aligned and offset conditions, the calculation seems to be going pretty well.  The SVM does not discriminate for 0 offset case in the 10 different runs, so far.  In general it was discriminating one of every two or so prior to this.

At this point we are handling the osLinear case just like we are handling the eye movement paths - removing the information for discrimination.

I suppose that if we use the more general osBioPhys case we will not have the same problem.  In that case, however, we will have to make the stimuli much longer and clip the 'warm-up' time.  Worries for the next phase.  

Closing.
